os:
  - linux
cache:
  pip: true
language: python
sudo: required
matrix:
  include:
  - python: '3.5'
    env: NOXSESSION="tests-3.5"
  - python: '3.6'
    env: NOXSESSION="tests-3.6"
  - python: '3.7'
    env: NOXSESSION="tests-3.7"
    dist: xenial
  - python: '3.8-dev'
    env: NOXSESSION="tests-3.8"
    dist: xenial

  - python: '3.7'
    env: NOXSESSION="lint"
    dist: xenial
  - python: '3.7'
    env: NOXSESSION="docs"
    dist: xenial

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/gdb; fi
  - pip install nox

script:
  - nox --non-interactive --session "$NOXSESSION"
